### ISSUE TITLE
Playoff data?

### ISSUE THREAD

**Issue by reeserich** [shufinskiy/nba_data#1]
Thank you for compiling this dataset and for making it easily accessible!

I was just wondering about the availability of post-season (as well as pre-season and all-start game) data. What was the rationale behind only using regular season data here?

Thank you again!

**Comment by shufinskiy** [comment]
Hi. 
Post-season data collection is different from season, game_id is not sequence. I plan build script for post-season data in June.

**Comment by shufinskiy** [comment]
@reeserich hello! I add playoff data in dataset

**Comment by reeserich** [comment]
Awesome! Thank you. Excited to dig around.
