### ISSUE TITLE
interpretation of 'PCTIMESTRING' in stats.nba.com file

### ISSUE THREAD

**Issue by jordannickerson** [shufinskiy/nba_data#3]
I'm still unsure of how game time is denoted in the nbastats_XXXX.csv files. I consulted the data dictionary, but it doesn't seem to be that  PCTIMESTRING represents the time to the end of the quarter. At best, it looks like this is the cumulative game time that has elapsed in the game multiplied by 60. However, there are still obvious errors. For instance, there are numerous games where a quarter ends, and the next quarter starts with a PCTIMESTRING value that is less than the previous value.

Can you offer clarification on this, and more importantly, how to estimate the current game time for each event in the file?

**Comment by shufinskiy** [comment]
@jordannickerson, thanks for you issue.
This is bug. For files from 1996 to 2020, PCTIMESTRING is seconds from start of game. And in the files 2021-2023 and all the playoffs, the raw data is in the form of MM:SS until the end of quarter. I need to think a little bit about which of the two options to leave.

> However, there are still obvious errors. For instance, there are numerous games where a quarter ends, and the next quarter starts with a PCTIMESTRING value that is less than the previous value.

Can you give me an example? I checked the files from 1996 to 2020 and found no incorrect data.

**Comment by shufinskiy** [comment]
Fix bug [commit](https://github.com/shufinskiy/nba_data/commit/125b09f28ddc378b21c170fe54a2b805cd1922fc)
