### ISSUE TITLE
G-league data

### ISSUE THREAD

**Issue by airhorns** [shufinskiy/nba_data#6]
Hi there -- thanks SO MUCH for putting this repo together and open sourcing it! 

With the new wnba data in place -- any chance you could drop the data for the G-leauge as well? It's super useful as extra data for padding out data used to fit / train models. It's `league_id` `20` in the NBA data api -- not sure about the other sources.

**Comment by shufinskiy** [comment]
@airhorns When adding WNBA data, I added a lot of code that simplifies the process of collecting/deploying new data, so I think I can take G-league into work this offseason. But it's more likely by October.

**Comment by airhorns** [comment]
I ended up scraping this myself with `nba_api` so absolutely no worries if you aren't feeling inclined!
